package:
  name: landmarkerio
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pathlib 1.0  # [py2k]
    - enum 0.4.4 # [py2k]
    - menpo 0.4.0a3
    - menpo3d 0.1.0a2
    - numpy 1.9.0
    - flask 0.10.1
    - flask-restful 0.2.12
    - cherrypy 3.6.0
    - joblib 0.8.4

test:
  imports:
    - landmarkerio

about:
  home: https://github.com/menpo/landmarkerio-server
  license: BSD
