package:
  name: landmarkerio
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pathlib 1.0  # [py2k]
    - enum 0.4.4 # [py2k]
    - menpo
    - menpo3d
    - numpy 1.9.0
    - flask 0.9
    - flask-restful 0.2.12
    - cherrypy
    - joblib

test:
  imports:
    - landmarkerio

about:
  home: https://github.com/menpo/landmarkerio-server
  license: BSD
